module.exports = [
    "Access Bank Plc",
    "First Bank Plc",
    "GT Bank Plc",
    "Zenith Bank Plc",
    "First City Monument Bank",
    "Fidelity Bank Plc",
    "Union Bank of Nigeria",
    "Unity Bank Plc",
    "Sterling Bank Plc",
    "Wema Bank Plc",
    "Kuda Bank Plc",
    "Polaris Bank Limited",
    "Providus Bank Limited",
  ];